import { ENUM_VEHICLE_MODEL_TYPE } from '@/modules/vehicle-model/enums/vehicle-model.enum';
import { ENUM_CARE_AREA } from '@/modules/care-area/enums/care-area.enum';
import { CARE_AREA_IDS } from '@/modules/care-area/constants/care-area.constant';
import { ServiceChecklistCreateRequestDto } from '../dtos/request/service-checklist.create.request.dto';

export const ServiceChecklistItem: ServiceChecklistCreateRequestDto[] = [
  {
    name: 'Bóng đèn trước',
    code: 'front_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Đèn Pha',
    code: 'high_beam',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Bóng đèn sau',
    code: 'rear_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Đèn Stop',
    code: 'stop_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Bóng đèn ĐH',
    code: 'dashboard_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Đèn Demi',
    code: 'demi_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Đèn xi-nhan trái',
    code: 'signal_left',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Đèn xi-nhan phải',
    code: 'signal_right',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Chớp xi-nhan',
    code: 'signal_flashing',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Kèn',
    code: 'horn',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Cóc đề',
    code: 'starter_switch',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Phóng đề',
    code: 'starter_relay',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Củ đề',
    code: 'starter_motor',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Than đề',
    code: 'starter_brush',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Nút chỉnh giờ',
    code: 'time_adjust_button',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '14',
  },
  {
    name: 'Ắc quy',
    code: 'battery',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '15',
  },
  {
    name: 'Điện áp sạc',
    code: 'charging_voltage',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '16',
  },
  {
    name: 'Ổ khóa',
    code: 'ignition_switch',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '17',
  },
  {
    name: 'Công tắc mở đèn',
    code: 'switch_light',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '18',
  },
  {
    name: 'Công tắc Cos/Pha',
    code: 'switch_high_low',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '19',
  },
  {
    name: 'Công tắc đề',
    code: 'switch_starter',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '20',
  },
  {
    name: 'Công tắc kèn',
    code: 'switch_horn',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '21',
  },
  {
    name: 'Công tắc xi-nhan',
    code: 'switch_signal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '22',
  },
  {
    name: 'Công tắc phanh trái',
    code: 'switch_brake_left',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '23',
  },
  {
    name: 'Công tắc phanh phải',
    code: 'switch_brake_right',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '24',
  },
  {
    name: 'Chảng ba',
    code: 'front_fork_bridge',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Chén cổ',
    code: 'steering_bearing_cup',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Sin che bụi chén cổ',
    code: 'steering_dust_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Tán chén cổ',
    code: 'steering_top_nut',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Bạc đạn bánh',
    code: 'wheel_bearing',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Phốt bánh trước (N)',
    code: 'front_wheel_seal_n',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Phốt bánh sau (L)',
    code: 'rear_wheel_seal_l',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Cục canh bánh',
    code: 'wheel_spacer',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Cốt + Tán bánh',
    code: 'axle_and_nut',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Ghi đông',
    code: 'handlebar',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Gù tay lái',
    code: 'handlebar_weight',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Phuộc trước',
    code: 'front_suspension',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Phuộc sau',
    code: 'rear_suspension',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_SUSPENSION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Cùm dầu',
    code: 'brake_master_cylinder',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Cupen',
    code: 'brake_cupen',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Piston heo dầu',
    code: 'brake_caliper_piston',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Cao su heo dầu',
    code: 'brake_caliper_rubber',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Sin piston',
    code: 'piston_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Bố thắng trước',
    code: 'front_brake_pad',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Đĩa thắng trước (T)',
    code: 'front_brake_disc_t',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Đĩa thắng sau (S)',
    code: 'rear_brake_disc_s',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Bố thắng sau',
    code: 'rear_brake_pad',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Tăng bua đùm',
    code: 'brake_drum_adjuster',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Cốt thắng sau',
    code: 'rear_brake_rod',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Tay thắng trái',
    code: 'left_brake_lever',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Tay thắng phải',
    code: 'right_brake_lever',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Ốc tay thắng trái',
    code: 'left_brake_lever_bolt',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Ốc tay thắng phải',
    code: 'right_brake_lever_bolt',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '14',
  },
  {
    name: 'Lò xo tay thắng',
    code: 'brake_lever_spring',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '15',
  },
  {
    name: 'Dây thắng sau',
    code: 'rear_brake_cable',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '16',
  },
  {
    name: 'Dây CBS',
    code: 'cbs_cable',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.BRAKE_FRONT_REAR],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '17',
  },
  {
    name: 'Áp suất bơm xăng',
    code: 'fuel_pump_pressure',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Áp suất buồng đốt',
    code: 'compression_pressure',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Kim phun',
    code: 'fuel_injector',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Bình xăng con (BXC)',
    code: 'carburetor',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Sin kim phun',
    code: 'injector_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Van gió',
    code: 'air_valve',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Họng ga',
    code: 'throttle_body',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Dù ga',
    code: 'throttle_slide',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Co xăng',
    code: 'fuel_pipe_joint',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Sin co xăng',
    code: 'fuel_pipe_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Bugi',
    code: 'spark_plug',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Chụp bugi',
    code: 'spark_plug_cap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Lọc gió',
    code: 'air_filter',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Sin bầu lọc gió',
    code: 'air_filter_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Lọc xăng + Sin',
    code: 'fuel_filter_and_seal',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '14',
  },
  {
    name: 'Dây / Ống xăng',
    code: 'fuel_hose',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '15',
  },
  {
    name: 'Mobin sườn',
    code: 'ignition_coil',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '16',
  },
  {
    name: 'Cảm biến',
    code: 'sensor',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '17',
  },
  {
    name: 'Bố 3 càng',
    code: 'bo_3_cang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Chuông nồi',
    code: 'chuong_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Lò xo trụ',
    code: 'lo_xo_tru',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Lò xo 3 càng',
    code: 'lo_xo_3_cang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Cao su 3 càng',
    code: 'cao_su_3_cang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Chén bi',
    code: 'chen_bi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Cánh quạt nồi',
    code: 'canh_quat_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Bộ bi nồi',
    code: 'bo_bi_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Bộ kẹp trượt',
    code: 'bo_kep_truot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Ắc nồi',
    code: 'ac_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Bộ đế + chặn 3 càng',
    code: 'bo_de_chan_3_cang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Tấm chặn bi',
    code: 'tam_chan_bi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Dây curoa',
    code: 'day_curoa',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Ron lóc nồi',
    code: 'ron_loc_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.POT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Bộ bạc đạn puly',
    code: 'bo_bac_dan_puly',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Bộ phốt puly N',
    code: 'bo_phot_puly_n',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Bộ phốt puly L',
    code: 'bo_phot_puly_l',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Bộ chốt puly',
    code: 'bo_chot_puly',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Phốt dên',
    code: 'phot_den',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Sin nồi',
    code: 'sin_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Phốt láp nhỏ',
    code: 'phot_lap_nho',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '6',
  },
  {
    name: 'Bộ láp',
    code: 'bo_lap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '7',
  },
  {
    name: 'Bộ bạc đạn láp',
    code: 'bo_bac_dan_lap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '8',
  },
  {
    name: 'Bạc đạn cốt bánh sau',
    code: 'bac_dan_cot_banh_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Phốt bánh (láp lớn)',
    code: 'phot_banh_lap_lon',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Ron hộp số/láp',
    code: 'ron_hop_so_lap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Bạc đạn gấp',
    code: 'bac_dan_gap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Phốt bạc đạn gấp',
    code: 'phot_bac_dan_gap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Cục canh bánh sau',
    code: 'cuc_canh_banh_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '14',
  },
  {
    name: 'Bạc đạn lóc nồi',
    code: 'bac_dan_loc_noi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.PULY_CLUTCH_SHAFT],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '15',
  },
  {
    name: 'Nhớt máy',
    code: 'nhot_may',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '0',
  },
  {
    name: 'Nhớt máy (Lớp đệm nhớt)',
    code: 'nhot_may_ldn',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Nhớt láp',
    code: 'nhot_lap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Nhớt láp (Lớp đệm nhớt)',
    code: 'nhot_lap_ldn',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Ty thăm nhớt',
    code: 'ty_tham_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '4',
  },
  {
    name: 'Sin ty thăm nhớt',
    code: 'sin_ty_tham_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '5',
  },
  {
    name: 'Nước mát',
    code: 'nuoc_mat',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '6',
  },
  {
    name: 'Két nước',
    code: 'ket_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '7',
  },
  {
    name: 'Nắp két nước',
    code: 'nap_ket_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '8',
  },
  {
    name: 'Bộ bơm nước',
    code: 'bo_bom_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '9',
  },
  {
    name: 'Quạt két nước',
    code: 'quat_ket_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '10',
  },
  {
    name: 'Ống nước',
    code: 'ong_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '11',
  },
  {
    name: 'Lúp B nước',
    code: 'lup_b_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Bộ phốt mâm lửa',
    code: 'bo_phot_mam_lua',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '13',
  },
  {
    name: 'Cuộn điện',
    code: 'cuon_dien',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING_SCOOTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '14',
  },
  {
    name: 'Vỏ xe trước',
    code: 'vo_xe_truoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '0',
  },
  {
    name: 'Vỏ xe sau',
    code: 'vo_xe_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '1',
  },
  {
    name: 'Van vòi T',
    code: 'van_voi_t',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '2',
  },
  {
    name: 'Van vòi S',
    code: 'van_voi_s',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '3',
  },
  {
    name: 'Mâm xe T',
    code: 'mam_xe_t',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '4',
  },
  {
    name: 'Mâm xe S',
    code: 'mam_xe_s',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '5',
  },
  {
    name: 'Nhông',
    code: 'nhong',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '6',
  },
  {
    name: 'Dây km',
    code: 'day_km',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '7',
  },
  {
    name: 'Bao tay (ống ga)',
    code: 'bao_tay_ong_ga',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '8',
  },
  {
    name: 'Dây ga',
    code: 'day_ga',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '9',
  },
  {
    name: 'Cao su treo máy',
    code: 'cao_su_treo_may',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '10',
  },
  {
    name: 'Thanh treo máy',
    code: 'thanh_treo_may',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '11',
  },
  {
    name: 'Bạc phuộc sau',
    code: 'bac_phuoc_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.SCOOTER],
    order: '12',
  },
  {
    name: 'Bọc biển số',
    code: 'boc_bien_so',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [
      ENUM_VEHICLE_MODEL_TYPE.SCOOTER,
      ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH,
    ],
    order: '13',
  },
  {
    name: 'B.đèn Trước',
    code: 'den_truoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '0',
  },
  {
    name: 'Pha',
    code: 'pha',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '1',
  },
  {
    name: 'B.đèn Sau',
    code: 'den_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '2',
  },
  {
    name: 'Stop',
    code: 'stop',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '3',
  },
  {
    name: 'Bóng đèn đồng hồ',
    code: 'den_dong_ho',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '4',
  },
  {
    name: 'Bóng đèn Demi',
    code: 'den_demi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '5',
  },
  {
    name: 'B.đèn xi-nhan T',
    code: 'den_xinhan_t',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '6',
  },
  {
    name: 'B.đèn xi-nhan P',
    code: 'den_xinhan_p',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '7',
  },
  {
    name: 'Cục chớp xi-nhan',
    code: 'cuc_chop_xinhan',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '8',
  },
  {
    name: 'Kèn',
    code: 'ken',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '9',
  },
  {
    name: 'Cóc đề',
    code: 'coc_de',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '10',
  },
  {
    name: 'Sin củ đề',
    code: 'sin_cu_de',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '11',
  },
  {
    name: 'Củ đề',
    code: 'cu_de',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '12',
  },
  {
    name: 'Than đề',
    code: 'than_de',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '13',
  },
  {
    name: 'Nút chỉnh giờ',
    code: 'nut_chinh_gio',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '14',
  },
  {
    name: 'Ắc quy',
    code: 'ac_quy',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '15',
  },
  {
    name: 'Điện áp sạc',
    code: 'dien_ap_sac',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '16',
  },
  {
    name: 'Ổ khóa',
    code: 'o_khoa',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '17',
  },
  {
    name: 'Công tắc mở đèn',
    code: 'cong_tac_mo_den',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '18',
  },
  {
    name: 'Cospha',
    code: 'cospha',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '19',
  },
  {
    name: 'Đề',
    code: 'de',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '20',
  },
  {
    name: 'Kèn (công tắc)',
    code: 'ken_cong_tac',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '21',
  },
  {
    name: 'Xinhan',
    code: 'xinhan',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '22',
  },
  {
    name: 'Phanh trái',
    code: 'phanh_trai',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '23',
  },
  {
    name: 'Phanh phải',
    code: 'phanh_phai',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.LIGHT_ELECTRIC_STARTER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '24',
  },
  {
    name: 'Áp suất bơm xăng',
    code: 'ap_suat_bom_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '0',
  },
  {
    name: 'Áp suất buồng đốt',
    code: 'ap_suat_buong_dot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '1',
  },
  {
    name: 'Kim phun',
    code: 'kim_phun',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '2',
  },
  {
    name: 'Bình xăng con (BXC)',
    code: 'binh_xang_con',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '3',
  },
  {
    name: 'Sin kim',
    code: 'sin_kim',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '4',
  },
  {
    name: 'Van gió',
    code: 'van_gio',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '5',
  },
  {
    name: 'Họng ga',
    code: 'hong_ga',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '6',
  },
  {
    name: 'Co xăng',
    code: 'co_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '7',
  },
  {
    name: 'Sin co xăng',
    code: 'sin_co_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '8',
  },
  {
    name: 'Bugi',
    code: 'bugi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '9',
  },
  {
    name: 'Chụp bugi',
    code: 'chup_bugi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '10',
  },
  {
    name: 'Lọc gió',
    code: 'loc_gio',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '11',
  },
  {
    name: 'Sin bầu lọc gió',
    code: 'sin_bau_loc_gio',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '12',
  },
  {
    name: 'Lọc xăng',
    code: 'loc_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '13',
  },
  {
    name: 'Sin lọc xăng',
    code: 'sin_loc_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '14',
  },
  {
    name: 'Dây/Ống xăng',
    code: 'day_ong_xang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '15',
  },
  {
    name: 'Mobin sườn',
    code: 'mobin_suon',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '16',
  },
  {
    name: 'Cảm biến',
    code: 'cam_bien',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.FUEL_IGNITION],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '17',
  },
  {
    name: 'Chảng ba',
    code: 'chang_ba',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '0',
  },
  {
    name: 'Chén cổ',
    code: 'chen_co',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '1',
  },
  {
    name: 'Sin che bụi chén cổ',
    code: 'sin_che_bui_chen_co',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '2',
  },
  {
    name: 'Tán chén cổ',
    code: 'tan_chen_co',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '3',
  },
  {
    name: 'Phuộc trước',
    code: 'phuoc_truoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '4',
  },
  {
    name: 'Ghi đông',
    code: 'ghi_dong',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '5',
  },
  {
    name: 'Gù',
    code: 'gu',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '6',
  },
  {
    name: 'Cùm dầu',
    code: 'cum_dau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '7',
  },
  {
    name: 'Cupen',
    code: 'cupen',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '8',
  },
  {
    name: 'Piston heo dầu',
    code: 'piston_heo_dau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '9',
  },
  {
    name: 'Cao su heo dầu',
    code: 'cao_su_heo_dau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '10',
  },
  {
    name: 'Sin piston',
    code: 'sin_piston',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '11',
  },
  {
    name: 'Bố thắng',
    code: 'bo_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '12',
  },
  {
    name: 'Đĩa thắng',
    code: 'dia_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '13',
  },
  {
    name: 'Tăng bua',
    code: 'tang_bua',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '14',
  },
  {
    name: 'Cốt thắng đùm',
    code: 'cot_thang_dum',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '15',
  },
  {
    name: 'Tay thắng',
    code: 'tay_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '16',
  },
  {
    name: 'Dây thắng',
    code: 'day_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '17',
  },
  {
    name: 'Dây dầu',
    code: 'day_dau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '18',
  },
  {
    name: 'Bạc đạn bánh',
    code: 'bac_dan_banh',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '19',
  },
  {
    name: 'Phốt bạc đạn N',
    code: 'phot_bac_dan_n',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '20',
  },
  {
    name: 'Phốt bạc đạn L',
    code: 'phot_bac_dan_l',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '21',
  },
  {
    name: 'Cục canh bánh',
    code: 'cuc_canh_banh',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '22',
  },
  {
    name: 'Cốt + Tán bánh',
    code: 'cot_tan_banh',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '23',
  },
  {
    name: 'Ruột xe',
    code: 'ruot_xe',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '26',
  },
  {
    name: 'Van vòi',
    code: 'van_voi',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '27',
  },
  {
    name: 'Vỏ xe',
    code: 'vo_xe',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.STEERING_FRONT_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '28',
  },
  {
    name: 'Pen đạp thắng đĩa',
    code: 'pen_dap_thang_dia',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '0',
  },
  {
    name: 'Cần đạp thắng',
    code: 'can_dap_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '8',
  },
  {
    name: 'Đũa thắng',
    code: 'dua_thang',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '9',
  },
  {
    name: 'Phốt bạc đạn',
    code: 'phot_bac_dan',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '12',
  },
  {
    name: 'Canh bánh',
    code: 'canh_banh',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '13',
  },
  {
    name: 'Dĩa',
    code: 'dia',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '14',
  },
  {
    name: 'Nhông sên dĩa',
    code: 'nhong_sen_dia',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '16',
  },
  {
    name: 'Cao su đỡ sên',
    code: 'cao_su_do_sen',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '17',
  },
  {
    name: 'Cao su đùm',
    code: 'cao_su_dum',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '18',
  },
  {
    name: 'Bạc đạn cùi dĩa',
    code: 'bac_dan_cui_dia',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '19',
  },
  {
    name: 'Phốt bạc đạn cùi dĩa',
    code: 'phot_bac_dan_cui_dia',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '20',
  },
  {
    name: 'Phuộc sau',
    code: 'phuoc_sau',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '21',
  },
  {
    name: 'Gấp',
    code: 'gap',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.TRANSMISSION_REAR_WHEEL],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '22',
  },
  {
    name: 'Ốc xả nhớt',
    code: 'oc_xa_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '3',
  },
  {
    name: 'Lóp đệm nhớt ốc xả nhớt',
    code: 'ldn_oc_xa_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '4',
  },
  {
    name: 'Lọc nhớt',
    code: 'loc_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '5',
  },
  {
    name: 'Sin lọc nhớt',
    code: 'sin_loc_nhot',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '6',
  },
  {
    name: 'Bơm nước',
    code: 'bom_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '10',
  },
  {
    name: 'Phốt nước',
    code: 'phot_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '11',
  },
  {
    name: 'Cốt bơm nước',
    code: 'cot_bom_nuoc',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '12',
  },
  {
    name: 'Lúp B',
    code: 'lup_b',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OIL_ENGINE_COOLING],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '15',
  },
  {
    name: 'Dây côn',
    code: 'day_con',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '2',
  },
  {
    name: 'Tay côn',
    code: 'tay_con',
    careArea: CARE_AREA_IDS[ENUM_CARE_AREA.OTHER],
    vehicleType: [ENUM_VEHICLE_MODEL_TYPE.MANUAL_OR_CLUTCH],
    order: '3',
  },
];
