export enum EnumActivityLogAction {
  userLoginCredential = 'userLoginCredential',
  userLoginGoogle = 'userLoginGoogle',
  userLoginApple = 'userLoginApple',
  userLogout = 'userLogout',
  userRefreshToken = 'userRefreshToken',
  userChangePassword = 'userChangePassword',
  userUpdateProfile = 'userUpdateProfile',
  userForgotPassword = 'userForgotPassword',
  userResetPassword = 'userResetPassword',
  userVerifyEmail = 'userVerifyEmail',
  userVerifiedEmail = 'userVerifiedEmail',
  userSendVerificationEmail = 'userSendVerificationEmail',
  userRevokeSession = 'userRevokeSession',
  userRevokeSessionByAdmin = 'userRevokeSessionByAdmin',
  adminSessionRevoke = 'adminSessionRevoke',
  adminUserCreate = 'adminUserCreate',
  adminUserUpdateStatus = 'adminUserUpdateStatus',
  adminUserUpdatePassword = 'adminUserUpdatePassword',
  adminUserImport = 'adminUserImport',
  adminDeviceRemove = 'adminDeviceRemove',
  adminRoleCreate = 'adminRoleCreate',
  adminRoleUpdate = 'adminRoleUpdate',
  adminRoleDelete = 'adminRoleDelete',
  adminServicePriceCreate = 'adminServicePriceCreate',
  adminServicePriceUpdate = 'adminServicePriceUpdate',
  adminServicePriceDelete = 'adminServicePriceDelete',
  adminServiceChecklistCreate = 'adminServiceChecklistCreate',
  adminServiceChecklistUpdate = 'adminServiceChecklistUpdate',
  adminServiceChecklistDelete = 'adminServiceChecklistDelete',
  adminApiKeyCreate = 'adminApiKeyCreate',
  adminApiKeyReset = 'adminApiKeyReset',
  adminApiKeyUpdate = 'adminApiKeyUpdate',
  adminApiKeyUpdateDate = 'adminApiKeyUpdateDate',
  adminApiKeyUpdateStatus = 'adminApiKeyUpdateStatus',
  adminApiKeyDelete = 'adminApiKeyDelete',

  // Vehicle Brand
  adminVehicleBrandCreate = 'adminVehicleBrandCreate',
  adminVehicleBrandUpdate = 'adminVehicleBrandUpdate',
  adminVehicleBrandUpdateStatus = 'adminVehicleBrandUpdateStatus',
  adminVehicleBrandDelete = 'adminVehicleBrandDelete',

  // Vehicle Model
  adminVehicleModelCreate = 'adminVehicleModelCreate',
  adminVehicleModelUpdate = 'adminVehicleModelUpdate',
  adminVehicleModelUpdateStatus = 'adminVehicleModelUpdateStatus',
  adminVehicleModelDelete = 'adminVehicleModelDelete',

  // Vehicle Service
  adminVehicleServiceCreate = 'adminVehicleServiceCreate',
  adminVehicleServiceUpdate = 'adminVehicleServiceUpdate',
  adminVehicleServiceUpdateStatus = 'adminVehicleServiceUpdateStatus',
  adminVehicleServiceDelete = 'adminVehicleServiceDelete',

  // User Vehicle
  adminUserVehicleCreate = 'adminUserVehicleCreate',
  adminUserVehicleUpdate = 'adminUserVehicleUpdate',
  adminUserVehicleDelete = 'adminUserVehicleDelete',
}
