export enum EnumPolicyAction {
  manage = 'manage',
  read = 'read',
  create = 'create',
  update = 'update',
  delete = 'delete',
}

export enum EnumPolicySubject {
  all = 'all',
  apiKey = 'apiKey',
  role = 'role',
  user = 'user',
  session = 'session',
  activityLog = 'activityLog',
  passwordHistory = 'passwordHistory',
  device = 'device',
  media = 'media',
  notification = 'notification',
  setting = 'setting',
  verification = 'verification',
  vehicleBrand = 'vehicleBrand',
  vehicleModel = 'vehicleModel',
  vehicleService = 'vehicleService',
  serviceCategory = 'serviceCategory',
  servicePrice = 'servicePrice',
  serviceChecklist = 'serviceChecklist',
  part = 'part',
  partType = 'partType',
  appointment = 'appointment',
  store = 'store',
  careArea = 'careArea',
  careRecord = 'careRecord',
  careRecordChecklist = 'careRecordChecklist',
  careRecordCondition = 'careRecordCondition',
  careRecordItem = 'careRecordItem',
  careRecordMedia = 'careRecordMedia',
  careRecordService = 'careRecordService',
  job = 'job',
  jobApplication = 'jobApplication',
  applicationReview = 'applicationReview',
  message = 'message',
  conversation = 'conversation',
  userVehicle = 'userVehicle',
}
