export enum ENUM_USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum ENUM_USER_TYPE {
  CUSTOMER = 'CUSTOMER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum ENUM_USER_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}
