import { ENUM_SERVICE_CHECKLIST_AREA } from "../types";

export const SERVICE_CHECKLIST_AREA_LABEL_MAP: Record<
  ENUM_SERVICE_CHECKLIST_AREA,
  string
> = {
  [ENUM_SERVICE_CHECKLIST_AREA.ENGINE]: "Động cơ",
  [ENUM_SERVICE_CHECKLIST_AREA.TRANSMISSION]: "Truyền động",
  [ENUM_SERVICE_CHECKLIST_AREA.SUSPENSION]: "Giảm xóc",
  [ENUM_SERVICE_CHECKLIST_AREA.BRAKE]: "Phanh",
  [ENUM_SERVICE_CHECKLIST_AREA.WHEEL]: "Bánh xe",
  [ENUM_SERVICE_CHECKLIST_AREA.ELECTRIC]: "Hệ thống điện",
  [ENUM_SERVICE_CHECKLIST_AREA.FUEL]: "Hệ thống nhiên liệu",
  [ENUM_SERVICE_CHECKLIST_AREA.COOLING]: "Làm mát",
  [ENUM_SERVICE_CHECKLIST_AREA.FRAME]: "Khung xe",
  [ENUM_SERVICE_CHECKLIST_AREA.BODY_CARE]: "Chăm sóc ngoại hình",
};
