export const BREADCRUMB_LABELS: Record<string, string> = {
  dashboard: "Tổng quan",
  stores: "Cửa hàng",
  employees: "Nhân viên",
  posts: "Bài viết",
  messages: "Tin nhắn",
  "vehicle-company": "Hãng xe",
  "vehicle-type": "Loại xe",
  "vehicle-parts": "Phụ tùng",
  category: "Danh mục",
  customers: "Khách hàng",
  invoices: "Hóa đơn",
  categories: "Danh mục phụ tùng",
  maintenance: "Bảo dưỡng",
  "maintenance-schedule": "Lịch hẹn",
  "part-types": "Danh mục phụ tùng",
  "service-categories": "Danh mục dịch vụ",
  "vehicle-services": "Dịch vụ xe máy",
  "vehicle-brands": "Hãng xe",
  "vehicle-models": "Dòng xe",
  roles: "Vai trò",
  permissions: "Phân quyền",
  products: "Sản phẩm",
  create: "Tạo mới",
  details: "Chi tiết",
  new: "Tạo mới",
  edit: "Chỉnh sửa",
};
