export const ROUTER_PATH = {
  INDEX: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  MESSAGES: "/messages",
  VEHICLE_COMPANY: "/vehicle-company",
  VEHICLE_TYPE: "/vehicle-type",
  CATEGORY: "/categories",
  CATEGORY_DETAILS: "/categories/:slug",
  CREATE_CATEGORY: "/categories/new",
  MAINTENANCE_SCHEDULE: "/maintenance-schedule",
  MAINTENANCE: "/maintenance",
  CUSTOMERS: "/customers",
  CUSTOMERS_DETAILS: "/customer/customer-details/:id",
  EMPLOYEES: "/employees",
  EMPLOYEES_DETAILS: "/employees/employee-details/:id",
  POSTS: "/posts",
  INVOICES: "/invoices",
  INVOICES_DETAILS: "/invoices/:id",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  PRODUCTS: "/products",
  PRODUCTS_DETAILS: "/products/:slug",
  CREATE_PRODUCT: "/products/new",
};
